const LAYOUT_SERVER_VIEW_MEETING = 4;
const OBJECT_CAMERA = 'camera';
const SERVER_ROLE_NVR = 4;
const ID_NVR_DEFAULT = 281;
const SITE_TYPE_REGISTER_DEFAULT = 'REGISTER_DEFAULT';
const HTTP_PARAMETER = "/live/nal/";
const WS_PARAMETER = "/evup/";
const SRC_XYZ = 'xyz';
const CDN_DEPLOY_VESION = 'dev';
const CONFIG_KEY = "-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCcCXnQbHvyWwwDXGd7wOvIRJch\nc/UTOpYCEUakeKj7HkwecsqbeOpcjONaPpXW+aDyaYoeoTLMzNeKo27BM5fpj88E\ntO97kHBqQXvwfjOxDIdWQcvmnQkM8vwhNKi/fH0+q421tNu7DzXhFHljFXMJOYOn\nZDreiE0BmUMsCALaJQIDAQAB\n-----END PUBLIC KEY-----";
const SITE_MODEL_REGISTER_DEFAULT = 72;

/*****************plate_type*****************/
//const VEHICLE_TYPE_CAR = 'CAR';
//const VEHICLE_TYPE_MOTOR = ' MOTOR';
///******************object_type****************/
//const OBJECT_VEHICLE_PERSIONAL = 'PERSIONAL';
//const OBJECT_VEHICLE_COMPANY = 'COMPANY';
//const OBJECT_VEHICLE_MILITARY = 'MILITARY';
//const OBJECT_VEHICLE_SPECIAL = 'SPECIAL';
const CDN_TYPE_2 = 'namtv';
const CDN_TYPE_3 = 'namrtc';
const URL_INIT_MODULE_VCAM = 'https://cms.vcam.viettel.vn/module_upload/96/1.2.10.tar.gz';
const SYSTEM_VCAM = 'vcam';
const INIT_SERVER_MODULE = 'updateServer';

const BCCS_IP_VCAM = '127.0.0.1';
module.exports = {
    LAYOUT_SERVER_VIEW_MEETING: LAYOUT_SERVER_VIEW_MEETING,
    OBJECT_CAMERA: OBJECT_CAMERA,
    ID_NVR_DEFAULT : ID_NVR_DEFAULT,
    SERVER_ROLE_NVR: SERVER_ROLE_NVR,
    SITE_TYPE_REGISTER_DEFAULT: SITE_TYPE_REGISTER_DEFAULT,
    HTTP_PARAMETER: HTTP_PARAMETER,
    WS_PARAMETER: WS_PARAMETER,
    SRC_XYZ: SRC_XYZ,
    CDN_DEPLOY_VESION: CDN_DEPLOY_VESION,
    CONFIG_KEY: CONFIG_KEY,
    CDN_TYPE_2 : CDN_TYPE_2,
    CDN_TYPE_3 : CDN_TYPE_3,
    SITE_MODEL_REGISTER_DEFAULT: SITE_MODEL_REGISTER_DEFAULT,
    BCCS_IP_VCAM : BCCS_IP_VCAM,
    URL_INIT_MODULE_VCAM : URL_INIT_MODULE_VCAM,
    SYSTEM_VCAM : SYSTEM_VCAM,
    INIT_SERVER_MODULE : INIT_SERVER_MODULE
};